### PR TITLE
fix: build on windows

### LINKED ISSUE #263: is support on windows?
error[E0432]: unresolved import `std::os::fd`
  --> E:\rust\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\foyer-storage-0.3.0\src\device\fs.rs:17:9
   |
17 |     os::fd::{AsRawFd, BorrowedFd, RawFd},
   |         ^^ could not find `fd` in `os`

### PR DESCRIPTION
**Pull request by spector-9**
### Currently foyer fails to compile on windows systems. This fixes the errors by adding some line that are cross platform or by adding crates that provide cross platform functionality.

- [x] I have written the necessary rustdoc comments
- [x] I have added the necessary unit tests and integration tests
- [ ] I have passed `make all` (or `make fast` instead if the old tests are not modified) in my local environment.
* the specific steps in the makefile are not compatible with windows. Ran cargo test though* 

close #263

### CODE REVIEW

File: foyer-storage/src/device/direct_file.rs [hunk 1]
```diff
@@ -123,14 +130,22 @@ impl DirectFileDevice {
...
         let mut buffer = asyncify_with_runtime(&self.runtime, move || {
-            #[cfg(target_family = "unix")]
-            use std::os::unix::fs::FileExt;
             #[cfg(target_family = "windows")]
-            use std::os::windows::fs::FileExt;
+            let read = {
+                let original = file.stream_position()?;
+                file.seek(std::io::SeekFrom::Start(offset))?;
+                let read = file.read(buf.as_mut())?;
+                file.seek(std::io::SeekFrom::Start(original))?;
```
Comment (spector-9) [inline foyer-storage/src/device/direct_file.rs:140]: We can skip this if you are sure that we don't need to seek the file to beginning because this is trying to emulate read_at behavior.

**Comment by MrCroxx** [comment]
Hi, @spector-9 . Thank you very much for your contribution! It would be great to have foyer run on Windows. But I cannot get bandwidth to do it. This PR helps a lot!!

I'll review it tomorrow. Thank you again for this PR. 🥰

File: foyer-storage/src/device/direct_file.rs (hunk 1 above)
Comment (MrCroxx) [reply foyer-storage/src/device/direct_file.rs:140]: Hi, @spector-9 . I'm not familar with Windows API. On Linux, positioned read/write will bypass  modification of fd, which is lighter and faster.

foyer aims to be a hybrid cache with optimal performance. seek io is not acceptable. (BTW, I think there is concurrent bug without a lock to protect seek and io)

Comment (spector-9) [reply foyer-storage/src/device/direct_file.rs:140]: @MrCroxx Hi, 
That's why I tried to keep unix and windows separate. On windows there's no read_at so there's no other option than to seek and call synchronous_read under the hood also synchronous_read moves the cursor to whatever happens to be the last position. 
To be more ergonomic I can call seek_read rather than manually seeking and then reading. I might also be able to remove the final seek that move the cursor to original position if it's not needed.

Comment (MrCroxx) [reply foyer-storage/src/device/direct_file.rs:140]: Oh, sorry about that. Seems my ios safari browser plugin distribes the github diff and I mistook the add and remove (realky wired...). I'll do a careful review tomorrow.

Comment (MrCroxx) [reply foyer-storage/src/device/direct_file.rs:140]: It revented the color in dark mode. 🤣

File: foyer-storage/src/device/direct_fs.rs [hunk 2]
```diff
@@ -162,14 +163,22 @@ impl Dev for DirectFsDevice {
...
             use std::os::unix::fs::FileExt;
             #[cfg(target_family = "windows")]
-            use std::os::windows::fs::FileExt;
+            let written = {
+                let original = file.stream_position()?;
+                file.seek(std::io::SeekFrom::Start(offset))?;
+                let written = file.write(buf.as_aligned())?;
+                file.seek(std::io::SeekFrom::Start(original))?;
+                written
+            };
```
Comment (MrCroxx) [inline foyer-storage/src/device/direct_fs.rs:177]: IIUC, functions provided by `std::os::windows::fs::FileExt` can be used here to do positioned read/write.

Manually doing seek + io may lead to concurrent problems.

https://doc.rust-lang.org/std/os/windows/fs/trait.FileExt.html

File: foyer-common/src/fs.rs [hunk 3]
```diff
@@ -14,13 +14,10 @@
...
-use nix::{errno::Errno, sys::statvfs::statvfs};
-
-/// Get the freespace of the device that contains the given path.
-pub fn freespace(path: impl AsRef<Path>) -> Result<usize, Errno> {
-    let stat = statvfs(path.as_ref())?;
-    let res = stat.blocks_available() as usize * stat.fragment_size() as usize;
-    Ok(res)
+/// Returns the available space. Available space in unix is space reserved for priviliged user +
+/// free space.
+pub fn freespace(path: impl AsRef<Path>) -> Result<u64, std::io::Error> {
```
Comment (MrCroxx) [inline foyer-common/src/fs.rs:19]:
```suggestion
pub fn freespace(path: impl AsRef<Path>) -> std::io::Result<u64> {
```

File: foyer-storage/src/device/direct_file.rs [hunk 4]
```diff
@@ -87,14 +85,23 @@ impl DirectFileDevice {
...
+
             #[cfg(target_family = "windows")]
-            use std::os::windows::fs::FileExt;
+            let written = {
+                let original = file.stream_position()?;
+                file.seek(std::io::SeekFrom::Start(offset))?;
+                let write = file.write(buf.as_aligned())?;
+                file.seek(std::io::SeekFrom::Start(original))?;
+                write
+            };
```
Comment (MrCroxx) [inline foyer-storage/src/device/direct_file.rs:100]: ditto

**Comment by MrCroxx** [comment]
> the specific steps in the makefile are not compatible with windows. Ran cargo test though*

BTW, what build system is most widely used on Windows? Is powershell script okay to replace Makefile?

File: foyer-storage/src/device/direct_fs.rs (hunk 2 above)
Comment (spector-9) [reply foyer-storage/src/device/direct_fs.rs]: Done also let me know if it's ok to use the allow_warning I used it for mut warning on unix since.

**Comment by spector-9** [comment]
> > the specific steps in the makefile are not compatible with windows. Ran cargo test though*
> 
> BTW, what build system is most widely used on Windows? Is powershell script okay to replace Makefile?

Honestly I would suggest since this is a rust project use something like nurfile so script/shell is cross-platform. Atleast that's what I use for my projects. If not then I can take a look at makefile and see what can be done to make it work on windows in separate PR.

File: foyer-storage/src/device/direct_file.rs [hunk 5]
```diff
@@ -87,14 +91,21 @@ impl DirectFileDevice {
...
-            use std::os::windows::fs::FileExt;
+            let written = {
+                let original = file.stream_position()?;
+                let written = file.seek_write(buf.as_aligned(), offset)?;
+                file.seek(std::io::SeekFrom::Start(original))?;
+                written
+            };
+
+            #[cfg(target_family = "unix")]
+            let written = { file.write_at(buf.as_aligned(), offset)? };
```
Comment (MrCroxx) [inline foyer-storage/src/device/direct_file.rs:107]: Hi, maybe there is some misunderstanding. IMO, there is no need to restore the fd seek position after doing positioned io.

File: foyer-storage/src/device/direct_file.rs [hunk 6]
```diff
@@ -12,11 +12,15 @@
 //  See the License for the specific language governing permissions and
 //  limitations under the License.
 
+#[cfg(unix)]
```
Comment (MrCroxx) [inline foyer-storage/src/device/direct_file.rs:15]: Please restore the `use` in the original position.

**Review by MrCroxx — COMMENTED** [review]
Generally LGTM. Thank you for your contribution again. 🥰

Would you mind my helping you solve the problems above?  Besides, I want to setup the CI pipeline on windows.

File: foyer-storage/src/device/direct_file.rs (hunk 5 above)
Comment (spector-9) [reply foyer-storage/src/device/direct_file.rs]: Yeah just wanted to make sure that we are not relying on write_at's behavior of not moving the cursor. Removed the useless seeking.

**Comment by spector-9** [comment]
@MrCroxx Let me know if I need to do something else. Thanks for your help.

**Comment by MrCroxx** [comment]
> @MrCroxx Let me know if I need to do something else. Thanks for your help.

Hi @spector-9 , Thank you a lot for the contribution. I'll update this branch to try to setup CI on Windows to see if it works.

I'm sorry that this may bring you some inconvenience. You need to update your local branch if needed.

If this CI passed, this PR will be merged ASAP.

Thank you again. 🥰 Wish you enjoy using and developing foyer ~

**Review by MrCroxx — APPROVED** [review]
CI on Windows passed! Thank you, @spector-9 . 🥰
